new_dialog_timeout: 1000000000000000000000000000000000000000000
use_chatgpt_api: true
return_n_generated_images: 0
n_chat_modes_per_page: 5
enable_message_streaming: false
chatgpt_price_per_1000_tokens: 0.002
gpt_price_per_1000_tokens: 0.02
whisper_price_per_1_min: 0.006